name: Service
extends: Component
main: ./index.js

providers: ${inputs.providers}
compute: ${inputs.compute}
functions: ${inputs.functions}

inputTypes:
  providers:
    type: Object
    default: ${context.providers}
    required: false
  compute:
    type: Object
    default: ${context.compute}
    required: false
  functions:
    type: Object
    default: ${context.functions}
    required: false
