type: aws-apigateway

inputTypes:
  name:
    type: string
    default: apig-${self.instanceId}
    description: Name of API gateway in AWS console
  roleArn:
    type: string
    required: true
    description: AWS Arn role for API gateway to assume
  routes:
    type: object
    required: true
    description: Declaration of routes
