environment:
  matrix:
    - NODEJS_VERSION: '8'

install:
  - ps: Install-Product node $env:NODEJS_VERSION
  - npm install --global npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install

test_script:
  - node --version
  - npm --version
  # NOTE: we only inlcude specific directories and skip integration tests on AppVeyor
  - npm run test:appveyor

matrix:
  fast_finish: true

shallow_clone: true

build: off
deploy: off

cache:
  - '%APPDATA%\npm-cache'
