type: s3-website-config
version: 0.2.0
core: 0.2.x

description: "A Serverless Component for configuring the static-website component"
license: Apache-2.0
author: "Serverless, Inc. <hello@serverless.com> (https://serverless.com)"
repository: "github:serverless/components"

inputTypes:
  rootBucketName:
    type: string
    required: true
  indexDocument:
    type: string
    default: index.html
  errorDocument:
    type: string
    default: error.html
  redirectBucketName:
    type: string
  redirectToHostName:
    type: string

outputTypes:
  rootBucketName:
    type: string
    description: The root bucket name
  indexDocument:
    type: string
    description: The used index document
  errorDocument:
    type: string
    description: The used error document
  redirectBucketName:
    type: string
    description: The name of the S3 redirect bucket
  redirectToHostName:
    type: string
    description: The hostname for the redirect
