type: aws-dynamodb
version: 0.2.0
core: 0.2.x

description: "Provision AWS DynamoDB tables with serverless components"
license: Apache-2.0
author: "Serverless, Inc. <hello@serverless.com> (https://serverless.com)"
repository: "github:serverless/components"

inputTypes:
  region:
    type: string
    required: true
    displayName: DynamoDB Table Region
    description: The region the table will be created in.
    example: us-east-1
  tables:
    type: object[]
    required: true
    displayName: DynamoDB Table Definitions
    description: Array of AWS DynamoDB table definitions
    example:
      - name: BlogPost
        hashKey: authorEmail
        rangeKey: title
        indexes:
          - name: BlogTitleIndex
            type: global
            hashKey: title
            rangeKey: createdAt
        schema:
          id: uuid
          authorName: string
          authorEmail:
            type: email
            options:
              required: true
          title: string
          content: binary
          tags: stringset
          published:
            type: boolean
            options:
              default: false
        options:
          timestamps: true

outputTypes:
  ddbtables:
    type: array
    description: Array containing information about all the deployed DynamoDB tables
