name: SimpleService
extends: Service

providers:
  aws:
    type: AwsProvider
    inputs:
      credentials:
        accessKeyId: AKIAJEMBJRTCIT24TDBA
        secretAccessKey: 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
      region: us-east-1

compute:
  type: AwsLambdaCompute
  inputs:
    provider: ${this.providers.aws}
    runtime: nodejs

functions:
  hello:
    compute: ${this.compute}
    handler: index.hello
    code: ./code
    memory: 1024
    timeout: 10

components:
  cron:
    type: Cron
    inputs:
      function: ${this.functions.hello}
      schedule: 1s
