type: tests-integration-iam-mock
version: 0.0.1

inputTypes:
  name:
    type: string
    required: true
  service:
    type: string
    default: default.serverless.service

outputTypes:
  id:
    type: string
  name:
    type: string
  service:
    type: string
  deploymentCounter:
    type: number
