type: mustache
version: 0.2.0
core: 0.2.x

description: "Mustache Serverless Component"
license: Apache-2.0
author: "Serverless, Inc. <hello@serverless.com> (https://serverless.com)"
repository: "github:serverless/components"

inputTypes:
  sourcePath:
    type: string
    required: true
  values:
    type: object
    required: false

outputTypes:
  renderedFilePath:
    type: string
    description: The path to the rendered file(s)
