name: AwsDynamoDB
extends: Component
main: ./index.js
version: 1.0.0

description: "Provision AWS DynamoDB tables with the Serverless Framework"
license: Apache-2.0
author: "Serverless, Inc. <hello@serverless.com> (https://serverless.com)"
repository: "github:serverless/components"

provider: ${inputs.provider}
tables: ${inputs.tables}

inputTypes:
  provider:
    type: AwsProvider
    required: true
  tables:
    type: object[]
    required: true
    displayName: DynamoDB Table Definitions
    description: Array of AWS DynamoDB table definitions
    example:
      - name: BlogPost
        hashKey: authorEmail
        rangeKey: title
        indexes:
          - name: BlogTitleIndex
            type: global
            hashKey: title
            rangeKey: createdAt
        schema:
          id: uuid
          authorName: string
          authorEmail:
            type: email
            options:
              required: true
          title: string
          content: binary
          tags: stringset
          published:
            type: boolean
            options:
              default: false
        options:
          timestamps: true
