type: cloudflare-worker-application

components:
  myWorker:
    type: cloudflare-workers
    inputs:
      accountId: ACCOUNT_ID_HERE
      credentials:
        authKey: CLOUDFLARE_AUTH_KEY_HERE
        authEmail: CLOUDFLARE_AUTH_EMAIL_HERE
      zoneId: ZONE_ID_HERE
      scriptPath: './index.js'
      route: '*example.com/path/*'
