# TODO: move this to the "examples" directory
# static website component

type: rg-staticweb
inputTypes:
  name:
    type: string
    default: rgfamilysite
  contentPath:
    type: string
    default: ./site
  templateValues:
    type: object
    default: {}
  contentIndex:
    type: string
    default: index.html
  contentError:
    type: string
    default: error.html
  hostingRegion:
    type: string
    default: us-east-1
  hostingDomain:
    type: string
    default: rgfamily.com
  aliasDomain:
    type: string
    default: www.rgfamily.com

components:
  renderedFiles:
    type: mustache
    inputs:
      sourcePath: ${input.contentPath}
      values: ${input.templateValues}
  rootDomainBucket:
    type: s3
    inputs:
      name: ${input.hostingDomain}
  rootDomainBucketPolicy:
    type: rg-s3policy
    inputs:
      bucketName: ${rootDomainBucket.name}
  siteContentUploader:
    type: rg-s3sync
    inputs:
      contentPath: ${renderedFiles.renderedFilePath}
      bucketName: ${rootDomainBucket.name}
  wwwDomainBucket:
    type: s3
    inputs:
      name: ${input.aliasDomain}
  rootDomainBucketConfig:
    type: rg-s3-website-config
    inputs:
      rootBucketName: ${rootDomainBucket.name}
      indexDocument: ${input.contentIndex}
      errorDocument: ${input.contentError}
      redirectBucketName: ${wwwDomainBucket.name}
      redirectToHostName: ${input.hostingDomain}
  siteCloudFrontConfig:
    type: rg-cloudfront
    inputs:
      name: ${input.name}
      defaultRootObject: ${input.contentIndex}
      originId: ${rootDomainBucket.name}
      originDomain: ${rootDomainBucket.name}.s3.amazonaws.com
      aliasDomain: ${input.aliasDomain}
      distributionEnabled: true
      loggingEnabled: false
      loggingBucket: logbucket
      loggingIncludeCookies: false
      loggingPrefix: cf-bucketname-
      priceClass: PriceClass_All      
  siteRoute53Config:
    type: rg-route53
    inputs:
      name: ${input.name}
      domainName: ${input.aliasDomain}
      dnsName: ${siteCloudFrontConfig.distribution.domainName} # d111111abcdef8.cloudfront.net
