# TODO: make this more reusable
type: s3-downloader
version: 0.2.0
core: 0.2.x

description: "A Serverless Component for downloading file when they are added to s3"
license: Apache-2.0
author: "Serverless, Inc. <hello@serverless.com> (https://serverless.com)"
repository: "github:serverless/components"

inputTypes:
  name:
    type: string
    default: my-s3-downloader
  eventGatewaySpace:
    type: string
    required: true
  eventGatewayApiKey:
    type: string
    required: true

components:
  downloaderLambda:
    type: aws-lambda
    inputs:
      name: ${input.name}
      handler: downloader.handler
      env:
        EVENT_GATEWAY_APIKEY: ${inputs.eventGatewayApiKey}
        FILES_TABLE: serverless-components-files
  downloaderSubscription:
    type: eventgateway
    inputs:
      event: fileUploaded
      space: ${inputs.eventGatewaySpace}
      eventGatewayApiKey: ${inputs.eventGatewayApiKey}
      lambdaArn: ${downloaderLambda.arn}
