# TODO: Make this more reusable
type: s3-uploader
version: 0.2.0
core: 0.2.x

description: "A Serverless Component for uploading files to AWS S3"
license: Apache-2.0
author: "Serverless, Inc. <hello@serverless.com> (https://serverless.com)"
repository: "github:serverless/components"

inputTypes:
  name:
    type: string
    default: my-s3-uploader
  eventGatewaySpace:
    type: string
    required: true
  eventGatewayApiKey:
    type: string
    required: true

components:
  uploaderLambda:
    type: aws-lambda
    inputs:
      name: ${input.name}
      handler: uploader.handler
      env:
        EVENT_GATEWAY_APIKEY: ${inputs.eventGatewayApiKey}
        BUCKET: serverless-components-files
  uploaderSubscription:
    type: eventgateway
    inputs:
      event: http
      method: POST
      path: ${input.name}
      space: ${inputs.eventGatewaySpace}
      eventGatewayApiKey: ${inputs.eventGatewayApiKey}
      lambdaArn: ${uploaderLambda.arn}
