# TODO: Make this more reusable
type: s3-uploader

inputTypes:
  name:
    type: string
    default: my-s3-uploader
  eventGatewaySpace:
    type: string
    required: true
  eventGatewayApiKey:
    type: string
    required: true

events:
  resumeUploaded:
    event-type: myapp.user.created
    data:
      foo: string
      bar:
        type: string
    # cloud-events-version: 0.1
    # content-type: application/json
    # source: ""
    # event-time: 1990-12-31T23:59:60Z
    # event-id: 66dfc31d-6844-42fd-b1a7-a489a49f65f3

components:
  uploaderLambda:
    type: aws-lambda
    inputs:
      name: ${input.name}
      handler: uploader.handler
      env:
        EVENT_GATEWAY_APIKEY: ${inputs.eventGatewayApiKey}
        BUCKET: serverless-components-files
  uploaderSubscription:
    type: eventgateway
    inputs:
      event: http
      method: POST
      path: ${input.name}
      space: ${inputs.eventGatewaySpace}
      eventGatewayApiKey: ${inputs.eventGatewayApiKey}
      lambdaArn: ${uploaderLambda.arn}
