type: rest-api
version: 0.2.0
core: 0.2.x

description: "REST API component."
license: Apache-2.0
author: "Serverless, Inc. <hello@serverless.com> (https://serverless.com)"
repository: "github:serverless/components"

inputTypes:
  gateway:
    type: string
    required: true
  eventGatewayApiKey:
    type: string
    required: false
  space:
    type: string
    required: false
  name:
    type: string
    required: false
    default: api-${self.instanceId}
  routes:
    type: object
    required: true

outputTypes:
  url:
    type: string
    description: The generated URL
  eventgateway:
    type: any
    description: Deployment information about the Event Gateway
  apigateway:
    type: any
    description: Deployment information about the API Gateway
  iam:
    type: any
    description: Deployment information about the IAM role
