type: aws-ecs-service
version: 0.2.0
core: 0.2.x

description: "Provision AWS ECS Service with Serverless Components"
license: Apache-2.0
author: "Serverless Inc. <hello@serverless.com> (https://serverless.com)"
repository: "github:serverless/components"

inputTypes:
  serviceName:
    type: string
    required: true
    example: myAwsEcsService
  cluster:
    type: string
  launchType:
    type: string
    enum: [EC2, FARGATE]
    example: FARGATE
  deploymentConfiguration:
    type: object
  desiredCount:
    type: integer
    example: 10
  healthCheckGracePeriodSeconds:
    type: integer
  networkConfiguration:
    type: object
  placementConstraints:
    type: array
  placementStrategy:
    type: array
  platformVersion:
    type: string
  role:
    type: string
  schedulingStrategy:
    type: string
    enum: [REPLICA, DAEMON]
  serviceRegistries:
    type: array
  taskDefinition:
    type: any
    required: true
    example: ${myECSTaskDefinition}
  loadBalancers:
    type: array

outputTypes:
  serviceArn:
    type: string
  serviceName:
    type: string
  clusterArn:
    type: string
  loadBalancers:
    type: array
  serviceRegisteries:
    type: string
  status:
    type: string
  desiredCount:
    type: integer
  runningCount:
    type: integer
  pendingCount:
    type: integer
  launchType:
    type: string
  platformVersion:
    type: string
  taskDefinition:
    type: string
  deploymentConfiguration:
    type: object
  deployments:
    type: array
  roleArn:
    type: string
  createdAt:
    type: any
  placementConstraints:
    type: array
  placementStrategy:
    type: array
  networkConfiguration:
    type: object
  healthCheckGracePeriodSeconds:
    type: integers
  schedulingStrategy:
    type: string

