type: aws-cloudfront
version: 0.2.0
core: 0.2.x

description: "Provision AWS Cloudfront distributions with serverless components"
license: Apache-2.0
author: "Serverless, Inc. <hello@serverless.com> (https://serverless.com)"
repository: "github:serverless/components"

inputTypes:
  name:
    type: string
    required: false
    default: dist-${self.instanceId}
  defaultRootObject:
    type: string
    required: true
  originDomain:
    type: string
    required: true
  aliasDomain:
    type: string
  distributionEnabled:
    type: boolean
    default: true
  loggingEnabled:
    type: boolean
    default: false
  loggingBucket:
    type: string
    default: ''
  loggingIncludeCookies:
    type: boolean
    default: false
  loggingPrefix:
    type: string
    default: ''
  priceClass:
    type: string

outputTypes:
  distribution:
    type: object
    description: Information about the CloudFront distributed
